public class multiplechoice extends javax.swing.JFrame {
     /**
     * Creates new form diceguessinggame
     */
    public multiplechoice() {
        initComponents();
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
         title = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        numberofcorrect = new javax.swing.JLabel();
        numberofincorrect = new javax.swing.JLabel();
        percentageofcorrect = new javax.swing.JLabel();
        output1 = new javax.swing.JLabel();
        output2 = new javax.swing.JLabel();
        output3 = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        answer_a_question1 = new javax.swing.JLabel();
        answer_b_question1 = new javax.swing.JLabel();
        answer_c_question1 = new javax.swing.JLabel();
        answer_a_question2 = new javax.swing.JLabel();
        answer_b_question2 = new javax.swing.JLabel();
        answer_c_question2 = new javax.swing.JLabel();
        answer_a_question3 = new javax.swing.JLabel();
        answer_b_question3 = new javax.swing.JLabel();
        answer_c_question3 = new javax.swing.JLabel();
        answer_a_question4 = new javax.swing.JLabel();
        answer_b_question4 = new javax.swing.JLabel();
        answer_c_question4 = new javax.swing.JLabel();
        answer_a_question5 = new javax.swing.JLabel();
        answer_b_question5 = new javax.swing.JLabel();
        answer_c_question5 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        input2 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        input4 = new javax.swing.JTextField();
        input5 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        instruction2 = new javax.swing.JLabel();
         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         title.setFont(new java.awt.Font("AachenDEEMed", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(153, 0, 0));
        title.setText("A Multiple Choice Quiz");
         instruction.setFont(new java.awt.Font("AachenDEEMed", 0, 16)); // NOI18N
        instruction.setForeground(new java.awt.Color(153, 0, 0));
        instruction.setText("Enter the correct option you think");
         numberofcorrect.setFont(new java.awt.Font("AachenDEEMed", 0, 16)); // NOI18N
        numberofcorrect.setForeground(new java.awt.Color(153, 0, 0));
        numberofcorrect.setText("Number of correct answers:");
         numberofincorrect.setFont(new java.awt.Font("AachenDEEMed", 0, 16)); // NOI18N
        numberofincorrect.setForeground(new java.awt.Color(153, 0, 0));
        numberofincorrect.setText("Number of incorrect answers:");
         percentageofcorrect.setFont(new java.awt.Font("AachenDEEMed", 0, 16)); // NOI18N
        percentageofcorrect.setForeground(new java.awt.Color(153, 0, 0));
        percentageofcorrect.setText("Percentage of correct answers:");
         output1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        output1.setText("0");
         output2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        output2.setText("0");
         output3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        output3.setText("0");
         question1.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        question1.setForeground(new java.awt.Color(102, 0, 0));
        question1.setText("1.Java was developed by:");
         question2.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        question2.setForeground(new java.awt.Color(102, 0, 0));
        question2.setText("2.How many bits are used to store a variable of type double in Java?");
         question3.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        question3.setForeground(new java.awt.Color(102, 0, 0));
        question3.setText("3.The range of values that can be stored in a variable of type long is:");
         question4.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        question4.setForeground(new java.awt.Color(102, 0, 0));
        question4.setText("4.How many bits are used to store a variable of type int in Java?");
         question5.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        question5.setForeground(new java.awt.Color(102, 0, 0));
        question5.setText("5.How many bits are used to store a variable of type byte in Java?");
         answer_a_question1.setText("\ta)  Sun Microsystems");
         answer_b_question1.setText("b) Microsoft");
         answer_c_question1.setText("c) Apple");
         answer_a_question2.setText("a) 8");
         answer_b_question2.setText("b) 16");
         answer_c_question2.setText("c) 64");
         answer_a_question3.setText("a)   0 to 4,294,967,295");
         answer_b_question3.setText("b)   0 to 2,147,483,647");
         answer_c_question3.setText("\t c)   -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807");
         answer_a_question4.setText("a)   64");
         answer_b_question4.setText("\t b)   52");
         answer_c_question4.setText("\t c)   32");
         answer_a_question5.setText("a)   16");
         answer_b_question5.setText("a)   32");
         answer_c_question5.setText("a)   8");
         input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
         input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input2ActionPerformed(evt);
            }
        });
         input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input3ActionPerformed(evt);
            }
        });
         input5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input5ActionPerformed(evt);
            }
        });
         submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
         instruction2.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        instruction2.setForeground(new java.awt.Color(153, 0, 0));
        instruction2.setText("check your answer and click Submit");
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(answer_a_question2)
                        .addGap(27, 27, 27)
                        .addComponent(answer_b_question2)
                        .addGap(26, 26, 26)
                        .addComponent(answer_c_question2)
                        .addGap(26, 26, 26)
                        .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer_c_question3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer_a_question3)
                                .addGap(18, 18, 18)
                                .addComponent(answer_b_question3))
                            .addComponent(question4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer_a_question4)
                                .addGap(18, 18, 18)
                                .addComponent(answer_b_question4)
                                .addGap(18, 18, 18)
                                .addComponent(answer_c_question4)
                                .addGap(28, 28, 28)
                                .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer_a_question5)
                                .addGap(18, 18, 18)
                                .addComponent(answer_b_question5)
                                .addGap(18, 18, 18)
                                .addComponent(answer_c_question5)
                                .addGap(38, 38, 38)
                                .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submit)
                                .addComponent(question5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(question2)
                                .addGap(238, 238, 238))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(question1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(answer_a_question1)
                                        .addGap(18, 18, 18)
                                        .addComponent(answer_b_question1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(answer_c_question1)
                                        .addGap(18, 18, 18)
                                        .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(title)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(instruction2)
                                        .addComponent(instruction)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numberofincorrect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(output2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numberofcorrect)
                                .addGap(43, 43, 43)
                                .addComponent(output1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(percentageofcorrect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(output3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answer_a_question1)
                            .addComponent(answer_b_question1)
                            .addComponent(answer_c_question1)
                            .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question2)
                            .addComponent(instruction2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answer_a_question2)
                            .addComponent(answer_b_question2)
                            .addComponent(answer_c_question2)
                            .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instruction)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberofcorrect)
                    .addComponent(output1)
                    .addComponent(question3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberofincorrect)
                            .addComponent(output2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answer_a_question3)
                            .addComponent(answer_b_question3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answer_c_question3)
                            .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(question4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_a_question4)
                    .addComponent(answer_b_question4)
                    .addComponent(answer_c_question4)
                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question5)
                    .addComponent(percentageofcorrect)
                    .addComponent(output3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_a_question5)
                    .addComponent(answer_b_question5)
                    .addComponent(answer_c_question5)
                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
         pack();
    }// </editor-fold>//GEN-END:initComponents
     private void input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input3ActionPerformed
     private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input1ActionPerformed
     private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String useranswer1, useranswer2, useranswer3, useranswer4, useranswer5;
        int numcorrect, numincorrect, totalquestions;
        double perofcorrect;
        numcorrect = 0;
        numincorrect = 0;
        totalquestions = 5;
        
        String[]useranswer = new String[5];
        for(int i = 0; i<=4; i++)
        {
            useranswer[1]=(input1.getText());
            useranswer[2]=(input2.getText());
            useranswer[3]=(input3.getText());
            useranswer[4]=(input4.getText());
            useranswer[5]=(input5.getText());
        }
        switch(useranswer[1])
        {
        case"A":case"a":
        numcorrect = numcorrect + 1;
        break;
        default:
         numincorrect = numincorrect + 1;
            break;
            
        }
        switch(useranswer[2])
        {
        case"C":case"c":
        numcorrect = numcorrect + 1;
        break;
        default:
         numincorrect = numincorrect + 1;
            break;
            
        }
        switch(useranswer[3])
        {
        case"C":case"c":
        numcorrect = numcorrect + 1;
        break;
        default:
         numincorrect = numincorrect + 1;
            break;
            
        }
        switch(useranswer[4])
        {
        case"C":case"c":
        numcorrect = numcorrect + 1;
        break;
        default:
         numincorrect = numincorrect + 1;
            break;
            
        }
        switch(useranswer[5])
        {
        case"C":case"c":
        numcorrect = numcorrect + 1;
        break;
        default:
         numincorrect = numincorrect + 1;
            break;
            
        }
        

        
        perofcorrect = ( numcorrect / 5) * 100;
        
        perofcorrect = perofcorrect * 1000;
        perofcorrect = Math.round(perofcorrect);
        perofcorrect = perofcorrect / 1000;
        
        
        output1.setText(String.valueOf(numcorrect));
        output2.setText(String.valueOf(numincorrect));
        output3.setText(String.valueOf("%" + perofcorrect));
        
        
    }//GEN-LAST:event_submitActionPerformed
     private void input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input2ActionPerformed
     private void input5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input5ActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiplechoice().setVisible(true);
            }
        });
    }
     // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer_a_question1;
    private javax.swing.JLabel answer_a_question2;
    private javax.swing.JLabel answer_a_question3;
    private javax.swing.JLabel answer_a_question4;
    private javax.swing.JLabel answer_a_question5;
    private javax.swing.JLabel answer_b_question1;
    private javax.swing.JLabel answer_b_question2;
    private javax.swing.JLabel answer_b_question3;
    private javax.swing.JLabel answer_b_question4;
    private javax.swing.JLabel answer_b_question5;
    private javax.swing.JLabel answer_c_question1;
    private javax.swing.JLabel answer_c_question2;
    private javax.swing.JLabel answer_c_question3;
    private javax.swing.JLabel answer_c_question4;
    private javax.swing.JLabel answer_c_question5;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel instruction2;
    private javax.swing.JLabel numberofcorrect;
    private javax.swing.JLabel numberofincorrect;
    private javax.swing.JLabel output1;
    private javax.swing.JLabel output2;
    private javax.swing.JLabel output3;
    private javax.swing.JLabel percentageofcorrect;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JButton submit;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
        
    }
    
}